### ISSUE TITLE
how to execute .bin files

### ISSUE THREAD

**Issue by seunex** [ytisf/theZoo#176]
Hello,
I am studying the behavior of some ransomware on a windows 10 virtual machine.
I am unable to execute some files that have a .bin file or convert it to .exe file to make it executable.
Can someone please point me towards how to do that?
Thank you

**Comment by ytisf** [comment]
Hey @seunex. That's a great question. A 'file' is just code for 'data'. What's in there does **not** depend on extension. Extension is just a hint for the OS as how to interpret that data. Each file has its own structure and manner of which to interpret that data. 
In a case where the data is of unknown content (such as the extension `bin`) I recommend using either the `file` command or, in a case where that does not work, the guys over at @ReFirmLabs created the wonderful [binwalk](https://github.com/ReFirmLabs/binwalk) which I could not recommend enough.  
Do please be careful with the binaries in this repository (and in general) as they will create damage to the machine you operate on unless you have taken very strong precautions. You **should not** need extension change in order to research these malware samples.
