### ISSUE TITLE
tyupkin

### ISSUE THREAD

**Issue by sudosuperman** [ytisf/theZoo#73]
hello, I was wondering about the tyupkin folder. i showed it to my friend and he said it was fake...

**Comment by CrazyLlama** [comment]
Hi,

These are all user submitted malware samples, I don't doubt that there may be malware that are different from the _core_ offerings originally sold to people but there may be changes unknown to us before.

So the answer is: no they're not fake. But we can't really give you any confirmation on whether they're going to be 100% originals due to the nature of _life_ in general.

**Comment by ArtiusAstro** [comment]
Can't you just run the malware in an appropriate environment, and see if its results are the same as the 'original' malware? 

Figure that's a foolproof method.

**Comment by ytisf** [comment]
Hey @sudosuperman @ArtiusAstro ,
There are ways to check if a file is malicious or not, and determine family and variant. However, many samples will have various variants of the same malware/copycats/just different samples with somewhat different hashes. 
Comparing to an 'original' malware really depends on what your define as your basepoint of 'original'. Earliest? The instance you're reading on the blog you're reading now? First big one? 
We attempt to maintain a certain level of confidence and hope we're doing an okay job.
